[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

remappings = [
  "@chainlink=lib/chainlink-brownie-contracts",
  "@chainlink/contracts-ccip=lib/ccip"
]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
